WebApplication4/Models/InviteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebApplication4.Attribut;

namespace WebApplication4.Models
{
    //model danych
    public class InviteModel
    {

        
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; } 
        public bool? WillaAttend { get; set; }
    }
}

WebApplication4/Controllers/InviteController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WebApplication4.BusinessLogic;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class InviteController : Controller
    {

        private FileBusinessLogic _fileBusinessLogic;

        public InviteController()
        {
            //tworzymy nową instację warstwy biznesowej w konstruktorze
            _fileBusinessLogic = new FileBusinessLogic();

        }
        //Get
        public ActionResult Index()
        {
            return View("InviteGuest");
        }

        //post
        [HttpPost]
        public ActionResult InviteGuest(InviteModel model)
        {

            if (ModelState.IsValid)
            {
                SendEmail(model);
                return View("Thanks", model);
            }
            return View("InviteGuest", model);
        }


        private void SendEmail(InviteModel mailModel)
        {
            //konfiguracja i autoryzacja ze skrzynką mailowa
            var smtpClient = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                UseDefaultCredentials = true,
                Credentials =
                new NetworkCredential("gym550182@gmail.com", "!QAZ2wsx#EDC")

            };
            //tworzenie nowej wiadomosci email
            var mailMessage = new MailMessage
            {
                Sender = new MailAddress("gym550182@gmail.com"),
                From = new MailAddress("gym550182@gmail.com"),
                To = { mailModel.Email},
                Subject = "temat maila"
,                Body = "tresc maila",
                IsBodyHtml = true

            };

            //wyslanie email
            smtpClient.Send(mailMessage);
        }

        //Get
        public ActionResult UploadFile()
        {
            return View();
        }

        //Post
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase photo)
        {
            //sprawdzammy czy wczytany plik nie jest pusty
            if (photo != null)
            {
                if (_fileBusinessLogic.CheckFileNameCorrectLength(Path.GetFileName(photo.FileName)))
                {
                    ViewBag.Dane = "Nazwa to " + Path.GetFileName(photo.FileName) +
                                   "rozmiar to : " + photo.ContentLength + " rozszerzenie : " +
                                   Path.GetExtension(photo.FileName);
                }

                else
                {
                    ViewBag.Dane = "Nazwa pliku nie może przekraczać 20 znaków";
                }



            }
            return View();
        }

    }
}

WebApplication4/Views/Invite/InviteGuest.cshtml
@using System.Web.Optimization
@model WebApplication4.Models.InviteModel

@{
    ViewBag.Title = "GetInvite";
}

<h2>GetInvite</h2>


@using (Html.BeginForm("InviteGuest","Invite",FormMethod.Post,new {@class= "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InviteModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2 isNumber" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WillaAttend, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.WillaAttend, new[] {
                    new SelectListItem() {Text = "Tak, przyjdę.", Value = bool.TrueString},
                    new SelectListItem() {Text = "Nie, nie przyjdę.", Value = bool.FalseString}
                }, "Wybierz opcję", new {@class = "form-control" })
            </div>
        </div>
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
   
}

WebApplication4/Views/Invite/Thanks.cshtml
@model WebApplication4.Models.InviteModel
@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks</h2>
<h1>Dziękujemy, @Model.Name   @Model.Surname!</h1>
@if (Model.WillaAttend == true) {
    @:Cieszymy się, że przyjdziesz do nas. Napoje są już w lodówce!
} else {
    @:Przykro nam, że nie możesz się zjawić, ale dziękujemy za informację.
}

WebApplication4/Views/Invite/UploadFile.cshtml
@{
    ViewBag.Title = "UpladFile";
}

<h2>UpladFile</h2>
@using (Html.BeginForm("UploadFile", "Invite", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
    <input type="file" name="photo" accept="image/jpg, image/jpeg" />

    <input type="submit" value="Create" class="btn btn-default" />
    </div>
                                                              
    }













@ViewBag.Dane

WebApplication4/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>